MEMORY
{
  /* NOTE 1 K = 1 KiBi = 1024 bytes */
  FLASH : ORIGIN = 0x00000000, LENGTH = 1024K 
  RAM : ORIGIN = 0x20000000, LENGTH = 128K - 1K
  PERSISTANT_BUFF: ORIGIN = ORIGIN(RAM) + LENGTH(RAM), LENGTH = 1K
}
_persistant_buff_start = ORIGIN(PERSISTANT_BUFF);
_persistant_buff_end   = ORIGIN(PERSISTANT_BUFF) + LENGTH(PERSISTANT_BUFF);