# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "2022-09-22"
components = [ "clippy", "rustfmt" ]
targets = [ "thumbv7em-none-eabihf"]
