[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF52840_xxAA"
rustflags = [
  # "-C", "linker=flip-link", Fix MEMORY.RAM not found
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
]

[alias]
rb = "run --bin"
rrb = "run --release --bin"

[env]
DEFMT_LOG = "info"
